import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SignedOut, SignedIn, SignInButton, SignOutButton} from "@clerk/nextjs";

import TopNav from "./_components/topnav.tsx";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
